# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Build

#어떤 브랜치에서든 코드가 push될 때마다 workflow가 실행
on:
  push:
    branches: [ "**" ]

jobs:
  build-bookmark-api:
    name: Build bookmark-api
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./bookmarker-api
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      # Maven build 작업시 권한으로 인한 접근 허용 
      - name: Build with Maven
        run: |
          chmod +x mvnw 
          ./mvnw verify

      # docker의 tty 명령어를 사용하기 위한 환경설정
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          ./mvnw clean package jib:dockerBuild -DskipTests
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t myimage:latest .
          docker tag myimage:latest ${{ secrets.DOCKER_USERNAME }}/bookmarker-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-api:latest
        env: 
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled

  ########################################
  # 2️⃣ bookmark-ui-nextjs 빌드 및 Docker 배포
  ########################################
  build-bookmarker-ui:
    name: Build bookmarker-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmark-ui-nextjs
    steps:
      # 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node.js 설정
      - name: Setup Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          
      # 의존성 설치
      - name: Install dependencies
        run: npm ci
        
      # ✅ .env.local 파일 생성
      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_CLIENT_SIDE_API_BASE_URL=${{ secrets.NEXT_PUBLIC_CLIENT_SIDE_API_BASE_URL }}" > .env.local
          echo "SERVER_SIDE_API_BASE_URL=${{ secrets.SERVER_SIDE_API_BASE_URL }}" >> .env.local

      # Next.js 빌드
      - name: Build
        run: npm run build

      # 메인 브랜치일 경우 Docker 이미지 빌드 & 배포
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          docker build -f Dockerfile.ui -t ${{ secrets.DOCKER_USERNAME }}/bookmark-ui-nextjs .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmark-ui-nextjs
